language: python
python:
  - "2.7.10"
  - "2.7.13"

cache:
  pip: true
  directories:
    - node_modules # NPM packages

before_install:
  # Install latest stable NodeJS version. Required for eslint.
  - nvm install stable
  # Install binary package for lxml to speed up build
  - sudo apt-get -qq update
  - sudo apt-get install -y python-lxml

before_script:
  - make deps-test
  # Install eslint, eslint-config-edx and their dependencies
  - make tools

script:
  - make quality-py
  - make quality-js
  - make test-py

after_success:
  - coveralls

addons:
  code_climate:
    repo_token: 8b6b72db7cca0082ac23c0d86062b40eb3761d65bdfaafa85c491a2e0b95f8bd
